#!/usr/bin/env bash
# Imprime del 1 al 20 y cuando llega a cierto numero
# imprime el mensaje del case

iterador=1

while [ $iterador -le 20 ];
do
    echo $iterador

    case $iterador in
    4) echo "bad luck from China" ;;
    9) echo "bad luck from Japan" ;;
    17) echo "bad luck from Italy" ;;
    esac
        iterador=$((iterador + 1))
done
