#!/usr/bin/env bash
#Script que configura un servidor Ubuntu con estos requisitos

cp /etc/hosts ~/hosts.new
sed -i 's/127\.[0].[0].[1]/127.0.0.2/' ~/hosts.new
sed -i '$a\8\.8\.8\.8    facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
